Controllers/SearchController.cs
using CFC.SearchFund.Models;
using CFC.SearchFund.UoW;
using System;
using System.Text;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;
using MailKit.Net.Smtp;

namespace CFC.SearchFund.Controllers
{
    [SessionState(System.Web.SessionState.SessionStateBehavior.ReadOnly)]
    public class SearchController : BaseController<CFCSearch_Result>
    {
        private SearchUnit _LogicUnit;

        public SearchUnit LogicUnit
        {
            get
            {
                if (_LogicUnit == null)
                    _LogicUnit = new SearchUnit((SearchRepo)Repository);

                return _LogicUnit;
            }
        }

        public SearchController(BaseRepository<CFCSearch_Result> repository)
            : base(repository)
        {

        }


        public ActionResult Index()
        {
            var subject_cl = LogicUnit.GetSubjects();
            //return Json(new { Text = "succes Index" }, JsonRequestBehavior.AllowGet);
            //ViewBag.SUBJECT_CL = new SelectList(new string[] { "Все", "Федеральные архивы" }.Union(subject_cl), "Все");
            ViewBag.SUBJECT_CL = new SelectList(subject_cl, "Id", "FullName");
            return View();
        }

        [HttpPost]
        public ActionResult Index(AdvancedModel model)
        {
            if (ViewBag.SUBJECT_CL == null)
            {
                var subject_cl = LogicUnit.GetSubjects();
                //return Json(new { Text = "succes Index(AdvancedModel model)" }, JsonRequestBehavior.AllowGet);
                ViewBag.SUBJECT_CL = new SelectList(subject_cl, "Id", "FullName");
            }
            
            if (model.DetailsViewKey == null)
                return View(model);

            if (model.PrewSearch != model.SearchString && model.PrewSearch != null)
            {
                model.DetailsViewKey = null;
                return View("Index", model);

            }

            //С использованием новой функции в БД - sp_CFCSearch2 11.02.2021 Salaman Andrey
            return IndexDetalized(model);
        }



        [HttpPost]
        public ActionResult IndexDetalized(AdvancedModel model)
        {

            if (ViewBag.SUBJECT_CL == null)
            {
                var subject_cl = LogicUnit.GetSubjects();
                //return Json(new { Text = "succes IndexDetalized(AdvancedModel model)" },JsonRequestBehavior.AllowGet);
                //ViewBag.SUBJECT_CL = new SelectList(new string[] { "Все", "Федеральные архивы" }.Union(subject_cl), "Все");
                ViewBag.SUBJECT_CL = new SelectList(subject_cl, "Id", "FullName");
            }

            if (model == null)
                return View();

            if (string.IsNullOrWhiteSpace(model.SearchString))
            {
                ModelState.Remove("Pattern");
            }

            var pageFrom = 0;
            var pageTo = model.PageCol;

            if (model.PageNumb == null)
            {
                pageFrom = 0;
                pageTo = model.PageCol;
            }
            else
            {
                var pageNumb = Convert.ToInt32(model.PageNumb);
                pageFrom = (pageNumb - 1) * model.PageCol + 1;
                pageTo = pageFrom + model.PageCol;
            }

            List<CFCSearch_Result> results;
            try
            {
                model.withNoErrors = true;
                //Использование новой функции SearchDetalized с дополнительными параметрами 10.02.2021 Salaman Andrey
                results = new List<CFCSearch_Result>(LogicUnit.SearchDetalized(model.SearchString.ToFullTextPattern(), model.SearchString.ToMatchPattern(), model.DetailsViewKey, pageFrom, pageTo,
                                                     model.Subject,
                                                     model.ArchiveInstitution,
                                                     model.ArchiveName,
                                                     model.FundPrefix,
                                                     model.FundNumb,
                                                     model.FundLetter,
                                                     Convert.ToInt32(model.InFundName),
                                                     Convert.ToInt32(model.InInventoryName),
                                                     Convert.ToInt32(model.InFundAnnotate),
                                                     Convert.ToInt32(model.InInventoryAnnotate),
                                                     Convert.ToInt32(model.InFundHistory),
                                                     Convert.ToInt32(model.InUnitName)));

            }

            catch (Exception e)
            {

                model.withNoErrors = false;
                results = new List<CFCSearch_Result>();
            }

            switch (model.Subject)
            {
                case null: break;
                case "Все": break;
                case "Федеральные архивы":
                    results = results.Where(x => x.ArchiveLevel == "a").ToList(); break;
                default:
                    results = results.Where(x => x.SubjectName.Trim().ToUpper() == model.Subject.Trim().ToUpper()).ToList(); break;
            }

            switch (model.ArchiveName)
            {
                case null: break;
                default:
                    results = results.Where(x => x.ArchiveName.Trim().ToUpper() == model.ArchiveName.Trim().ToUpper() || x.ArchiveNameShort.Trim().ToUpper() == model.ArchiveName.Trim().ToUpper()).ToList(); break;
            }
            switch (model.ArchiveInstitution)
            {
                case null: break;
                case "Все": break;
                default:
                    results = results.Where(x => x.ArchiveName.Trim().ToUpper() == model.ArchiveInstitution.Trim().ToUpper() || x.ArchiveNameShort.Trim().ToUpper() == model.ArchiveInstitution.Trim().ToUpper()).ToList(); break;
            }
            //if (!string.IsNullOrWhiteSpace(model.YearFrom))
            //{
            //    results = results.Where(x => x.YearFrom.ToInt(0) >= model.YearFrom.ToInt(0) ||
            //        model.YearFrom == "" && x.YearTo != "").ToList();
            //}


            model.Results = results;

            return View(model);
        }

        public ContentResult AjaxGetSub(Guid? Subject)
        {
            var Arhives = LogicUnit.GetArhives(Subject);  /*new List<string>() { "Архив номер один", "Какой-то еще Архив", "Архив для кого-то", "Кому-то нужный Архив", "Чей-то архив", "Никому не нужный Архив" };*/

            SelectList listArhives = new SelectList(Arhives, "Id", "FullName");

            if (listArhives.Count() != 0)
            {
                string result = "";
                foreach (SelectListItem item in listArhives)
                {
                    result += "<option data-id = \" " + item.Value + " \" value=\' " + item.Text + "\' ></ option >";
                }
                return Content(result);
            }
            else
            {
                return Content(listArhives.Count().ToString());
            }



        }

        public ActionResult Advanced()
        {
            var subject_cl = LogicUnit.GetSubjects();
            //return Json(new { Text = "succes Advanced()" },JsonRequestBehavior.AllowGet);
            //ViewBag.SUBJECT_CL = new SelectList(new string[] { "Все", "Федеральные архивы" }.Union(subject_cl), "Все");
            ViewBag.SUBJECT_CL = new SelectList(subject_cl, "Id", "FullName");


            return View();
        }

        public ActionResult SearchResult(IEnumerable<CFCSearch_Result> data)
        {
            ViewBag.Message = "Это частичное представление.";
            return PartialView(data);
        }

        public ActionResult DetailsModal(System.Guid ID, int Kind)
        {
            CFCEntities cfc = new CFCEntities();

            //var kind = int.Parse(Url.RequestContext.RouteData.Values["kind"].ToString());
            //var id = new Guid(Url.RequestContext.RouteData.Values["id"].ToString());

            var kind = int.Parse(Kind.ToString());
            var id = ID;

            InfoDetails model = new InfoDetails();

            if (kind == 703)
            {
                model.unit = cfc.vCFCSearch_Unit.SingleOrDefault(x => x.ID == id);
            }
            if (kind == 702)
            {
                model.inventory = cfc.vCFCSearch_Inventory.SingleOrDefault(x => x.ID == id);
            }
            if (kind == 701)
            {
                model.fund = cfc.vCFCSearch_Fund.SingleOrDefault(m => m.ID == id);
            }
            if (kind == 700)
            {
                model.archive = cfc.tblARCHIVE.SingleOrDefault(x => x.ID == id);
            }
            if (model.unit != null)
            {
                model.inventory = cfc.vCFCSearch_Inventory.SingleOrDefault(x => x.ISN_INVENTORY == model.unit.ISN_INVENTORY);
            }
            if (model.inventory != null)
            {
                model.fund = cfc.vCFCSearch_Fund.SingleOrDefault(x => x.ISN_FUND == model.inventory.ISN_FUND);
            }
            if (model.fund != null)
            {
                model.archive = cfc.tblARCHIVE.SingleOrDefault(x => x.ISN_ARCHIVE == model.fund.ISN_ARCHIVE);
            }
            if (model.archive != null)
            {
                model.subject = cfc.tblSUBJECT_CL.SingleOrDefault(x => x.ISN_SUBJECT == model.archive.ISN_SUBJECT);
            }
            //var data  = ViewBag.Message = "Это частичное представление.";
            return PartialView("Partial/DetailsModal", model);
        }

        public ActionResult SleepResult(string TYPE)
        {
            Thread.Sleep(5000);
            //var model = TYPE;
            return Content(TYPE);

Views/Search/Partial/DetailsModal.cshtml
@using CFC.SearchFund.Models
@model CFC.SearchFund.Models.InfoDetails

@{
    ViewBag.Title = "DetаilsModal";
}





    <div class="modal-header caption">
       
            <div class="container p-0">
              <div class="row justify-content-between">
                <div class="col-8">
                     <h5 class="modal-title">
                         
            @{ 
                if (Model.archive != null)
                {
            <a>@Model.archive.NAME_SHORT</a>
                } else {
                    <a>Подробная информация</a>
                    }
                }
                     </h5>
 @{ 
                 if (Model.subject != null)
            {
                    <h6 class="m-0 subjectText">
                        @Model.subject.NAME
                    </h6>
            }

             }
              
            </div>
            <div class="col-4 text-right align-self-end pl-0">
               @{ 
                   if (Model.unit != null)
                   {
                    <h6 class="text-right m-0 yearsText">
               
                <b>
                    @(Model.unit.START_YEAR.HasValue ? Model.unit.START_YEAR.Value.ToString() : "...")
                    -
                    @(Model.unit.END_YEAR.HasValue ? Model.unit.END_YEAR.Value.ToString() : "...")
                </b>
            </h6>
                }
                else
                {
                    if (Model.inventory != null)
                    {
                         <h6 class="text-right m-0 yearsText">
                        @(Model.inventory.DOC_START_YEAR.HasValue ? Model.inventory.DOC_START_YEAR.Value.ToString() : "...")
                        -
                        @(Model.inventory.DOC_END_YEAR.HasValue ? Model.inventory.DOC_END_YEAR.Value.ToString() : "...")
                        </h6>
                        }
                        else
                        {
                            if (Model.fund != null)
                            {
                             <h6 class="text-right m-0 yearsText">               
                                <b>
                                    @(Model.fund.DOC_START_YEAR.HasValue ? Model.fund.DOC_START_YEAR.Value.ToString() : "...")
                                    -
                                    @(Model.fund.DOC_END_YEAR.HasValue ? Model.fund.DOC_END_YEAR.Value.ToString() : "...")  гг.
                                </b>
                            </h6>
                            }
                        }
                    } 
                }
                </div> 
              </div>
            </div>
        
        <button type="button" class="close" data-dismiss="modal">&times;</button>

    </div>
    <div class="modalBody thumbnail">
        <div class="modal-body ">
            <div class="textModal">
                @{

                    if (Model.archive != null)
            {
            <h5 class="textSelected">
                Полное название архива:
            </h5>
            <p>
                @Model.archive.NAME
            </p>
            }
            if (Model.unit != null)
            {
          
            <h5 class="textSelected">
                Единица № @Model.unit.UNIT_NUM :
            </h5>
            <p>
                @Model.unit.NAME
            </p>
            }
            if (Model.inventory != null)
            {
            
            <h5 class="textSelected">
                Опись № @Model.inventory.INVENTORY_NUM :
            </h5>
            <p>
                @Model.inventory.INVENTORY_NAME
            </p>

            if (!String.IsNullOrWhiteSpace(Model.inventory.ANNOTATE)) 
                { 
            <h5 class="textSelected">
                Аннотация описи:
            </h5>
            <p>
                @Model.inventory.ANNOTATE
            </p>
            }
           }
            if (Model.fund != null)
            {
            
            <h5 class="textSelected">
                Фонд № @Model.fund.FUND_NUM :
            </h5>
            <p>
                @Model.fund.FUND_NAME_FULL
            </p>

            if (!String.IsNullOrWhiteSpace(Model.fund.ANNOTATE))
             {
            <h5 class="textSelected">
                Аннотация фонда:
            </h5>
            <p>
                @Model.fund.ANNOTATE
            </p> 
             }
            if (!String.IsNullOrWhiteSpace(Model.fund.FUND_HISTORY))
              {
            <h5 class="textSelected">
                Историческая справка фонда:
            </h5>
            <p>
                @Model.fund.FUND_HISTORY
            </p>
            }
            }
            
                }
            </div>

            <button type="button" class="btn btn-outline-success btn-default caption-link modalClose" data-dismiss="modal">Закрыть</button>
        </div>

    </div>

Views/Search/Partial/SearchPanel.cshtml
@model CFC.SearchFund.Models.AdvancedModel


<nav class="navbar navbar-expand-lg sticky-top navbar-light sticky-top bg-light justify-content-between">

    <a class="navbar-brand" href="@Html.Raw(Url.Action("Index","Search"))">
        <img src="~/Content/Images/search.svg" width="30" height="30" class="d-inline-block align-top" alt="">
        <span class="visibleMd">Поиск по фонду</span>
    </a>


    <div class="input-group inputPlane mr-2 ">
        @Html.TextBoxFor(model => model.PrewSearch, new { @id = "prewSearch", @style = "display:none" })
        @Html.TextBoxFor(model => model.SearchString, new { @class = "form-control  mr-sm-2 my-2", @id = "searchString", type = "search", placeholder = "Введите текст для поиска...", aria_label = "Search", aria_describedby = "sizing-addon1" })

        <div><i class="fa fa-sliders ml-2 mr-2 fa-2x config confOff advanced__link_search "></i></div>
    </div>
    <button class="btn btn-outline-success my-2 my-sm-0 search" type="submit" name="DetailsViewKey" value="@null">Поиск</button>
    <button id="bClear" class="btn btn-outline-dark my-2 ml-2 my-sm-0" type="button">Очистить</button>
</nav>
@Html.Partial("Partial/SearchPanelAdvanced")
<script type="text/javascript">
    $(document).ready(function () {

        $('#prewSearch')[0].value = $('#searchString')[0].value;
        console.log($('#prewSearch')[0].value);

    });
    $('#bClear').click(function Clear() {
        $('.form-control').val("");
        $('body input:checkbox').prop('checked', false);

    });
</script>

Views/Search/Partial/SearchResultCategories.cshtml
@using CFC.SearchFund.Models
@model IEnumerable<CFCSearch_Result>

@{
    ViewBag.Title = "Результаты поиска";
}


<div class="container pt-md-4">

    <div>
        @*<h5>Найдено:</h5>@* @Model.Count</h5>*@

    </div>
    <div class="modalDetails">
        <!-- Modal -->
        <div id="detailsModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-lg ">

                <!-- Modal content-->
                <div class="modal-content ">


                </div>

            </div>
        </div>
    </div>

    <div>

        <div>
            <p class="blockquote">Найдено @Model.Count() результатов.</p>
        </div>


        @{

            if (Model.Count() == 0)
            {
                <div>
                    <p class="blockquote">
                        Извините, по Вашему запросу ничего не найдено. Попробуйте повторить запрос, изменив некоторые фильтры.
                    </p>
                </div>
            }
            else
            {

                //foreach (var gitem in Model.GroupBy(l => l.Header))
                //{
                @*<div>
                        <p class="blockquote">Найдено @Model результатов:</p>
                    </div>*@
                <div class="@*blockType*@ container">
                    <div class="row">
                        <div class=" pt-md-3 thumbnail minCard col">
                            <div class="card caption">
                                <div class="card-header headerSize text-center">
                                    <img class="cardLogoFund" src="~/Content/Images/logoType/fund.png"><img />
                                    <h6 class="mt-2 cardTypeHeader"> Фонды </h6>
                                </div>
                                <div class="card-body bodyCardSize">
                                    @*<h6 class="card-title">@item.ArchiveName</h6>*@
                                    <div class="arhiveNameSize"><p class="card-text"> <i class="fa fa-bookmark fa-sm" style="color:#983a42;"></i> Найдено: -- фондов</p></div>
                                    <a class="btn btn-outline-success caption-link btn-default " data-toggle="modal" data-target="#detailsModal">Показать все</a>
                                </div>
                            </div>
                        </div>
                        <div class="margin">
                        </div>


                        <div class=" pt-md-3 thumbnail minCard col">
                            <div class="card caption ">
                                <div class="card-header headerSize text-center">
                                    <img class="cardLogoFund" src="~/Content/Images/logoType/history.png"><img />
                                    <h6 class="mt-2 cardTypeHeader"> Исторические справки фондов </h6>
                                </div>
                                <div class="card-body bodyCardSize">
                                    @*<h6 class="card-title">@item.ArchiveName</h6>*@
                                    <div class="arhiveNameSize"><p class="card-text"> <i class="fa fa-bookmark fa-sm" style="color:#983a42;"></i> Найдено: -- исторических справок фондов</p></div>
                                    <a class="btn btn-outline-success caption-link btn-default " data-toggle="modal" data-target="#detailsModal">Показать все</a>
                                </div>
                            </div>
                        </div>

                        <div class="margin">
                        </div>


                        <div class=" pt-md-3 thumbnail minCard col">
                            <div class="card caption ">
                                <div class="card-header headerSize text-center">
                                    <img class="cardLogoFund" src="~/Content/Images/logoType/annotatFund.png"><img />
                                    <h6 class="mt-2 cardTypeHeader"> Аннотации фондов </h6>
                                </div>
                                <div class="card-body bodyCardSize">
                                    @*<h6 class="card-title">@item.ArchiveName</h6>*@
                                    <div class="arhiveNameSize"><p class="card-text"> <i class="fa fa-bookmark fa-sm" style="color:#983a42;"></i> Найдено: -- аннотаций фондов</p></div>
                                    <a class="btn btn-outline-success caption-link btn-default " data-toggle="modal" data-target="#detailsModal">Показать все</a>
                                </div>
                            </div>
                        </div>

                        <div class="margin">
                        </div>
                    </div>
                    <div class="row">

                        <div class=" pt-md-3 thumbnail minCard col">
                            <div class="card caption ">
                                <div class="card-header headerSize text-center">
                                    <img class="cardLogoFund" src="~/Content/Images/logoType/list.png"><img />
                                    <h6 class="mt-2 cardTypeHeader"> Описи </h6>
                                </div>
                                <div class="card-body bodyCardSize">
                                    @*<h6 class="card-title">@item.ArchiveName</h6>*@
                                    <div class="arhiveNameSize"><p class="card-text"> <i class="fa fa-bookmark fa-sm" style="color:#983a42;"></i> Найдено: -- описей</p></div>
                                    <a class="btn btn-outline-success caption-link btn-default " data-toggle="modal" data-target="#detailsModal">Показать все</a>
                                </div>
                            </div>
                        </div>

                        <div class="margin">
                        </div>


                        <div class=" pt-md-3 thumbnail minCard col">
                            <div class="card caption ">
                                <div class="card-header headerSize text-center">
                                    <img class="cardLogoFund" src="~/Content/Images/logoType/annotatList.png"><img />
                                    <h6 class="mt-2 cardTypeHeader"> Аннотации описей </h6>
                                </div>
                                <div class="card-body bodyCardSize">
                                    @*<h6 class="card-title">@item.ArchiveName</h6>*@
                                    <div class="arhiveNameSize"><p class="card-text"> <i class="fa fa-bookmark fa-sm" style="color:#983a42;"></i> Найдено: -- аннотаций описей</p></div>
                                    <a class="btn btn-outline-success caption-link btn-default " data-toggle="modal" data-target="#detailsModal">Показать все</a>
                                </div>
                            </div>
                        </div>

                        <div class="margin">
                        </div>


                        <div class=" pt-md-3 thumbnail minCard col">
                            <div class="card caption ">
                                <div class="card-header headerSize text-center">
                                    <img class="cardLogoFund" src="~/Content/Images/logoType/doc.png"><img />
                                    <h6 class="mt-2 cardTypeHeader"> Единицы хранения </h6>
                                </div>
                                <div class="card-body bodyCardSize">
                                    @*<h6 class="card-title">@item.ArchiveName</h6>*@
                                    <div class="arhiveNameSize"><p class="card-text"> <i class="fa fa-bookmark fa-sm" style="color:#983a42;"></i> Найдено: -- единиц хранения</p></div>
                                    <a class="btn btn-outline-success caption-link btn-default " data-toggle="modal" data-target="#detailsModal">Показать все</a>
                                </div>
                            </div>

                        </div>
                        <div class="margin">
                        </div>
                    </div>
                </div>
                <img id="loadImg" src="~/Content/Images/load.gif" />
                <div class="margin">
                </div>
            }
        }

    </div>
</div>
<script type="text/javascript">

        $(function () {
            $.ajaxSetup({ cache: false });
            $(".openDetails").click(function (e) {
                var id = $(this).attr("dataID");
                var kind = $(this).attr("dataKind");
                e.preventDefault();
                $.get('@Url.Action("DetailsModal","Search" )' + '?ID=' + id + '&Kind=' + kind, function (data) {
                    @*$.get('@Url.Action("DetailsModal","Search" )',function (data) {*@
                    $('.modal-content').html(data);
                });
            });
    })
     @*$(function () {
            $.ajaxSetup({ cache: false });
         $(".seeAll").click(function (e) {
             var type = $(this).attr("dataType");
             console.log(type);
                e.preventDefault();
                $.get('@Url.Action("SleepResult", "Search" )' + '?TYPE=' + type , function (data) {
                    $('.contentResultType').html(data);
                });
            });
        })*@
    $(function () {
        $.ajaxSetup({ cache: false });
            var type = "fuf";
            console.log(type);
             //e.preventDefault();
        $.get('@Url.Action("SleepResult", "Search" )' + '?TYPE=' + type, onAjaxSuccess)
        StartLoadingAnimation();
    })
    function onAjaxSuccess(data) {
        console.log("result");
        console.log(data);
        StopLoadingAnimation();
    }
    function StartLoadingAnimation() // - функция запуска анимации
{
  // найдем элемент с изображением загрузки и уберем невидимость:
  var imgObj = $("#loadImg");
        imgObj.show();


  // вычислим в какие координаты нужно поместить изображение загрузки,
  // чтобы оно оказалось в серидине страницы:
  var centerY = $(window).scrollTop() + ($(window).height() + imgObj.height())/2;
  var centerX = $(window).scrollLeft() + ($(window).width() + imgObj.width())/2;

  // поменяем координаты изображения на нужные:
        imgObj.offset({ top: centerY, left: centerX });
}

function StopLoadingAnimation() // - функция останавливающая анимацию
{
  $("#loadImg").hide();
}
</script>